/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.main;

import controller.Controller;
import domain.Servis;
import domain.Serviser;
import form.clients.Klijenti;
import form.components.Komponente;
import form.configurations.KonfiguracijaPregled;
import form.configurations.KonfiguracijaUnos;
import form.servis.model.TableModelServis;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import session.Session;

/**
 *
 * @author Ivan
 */
public class Main extends javax.swing.JFrame {
    Serviser serviser = Session.getInstance().getServiser();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        populate();
        setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        pnlServiser = new javax.swing.JPanel();
        lblIme = new javax.swing.JLabel();
        lblPrezime = new javax.swing.JLabel();
        lblKorisnickoIme = new javax.swing.JLabel();
        btnKlijenti = new javax.swing.JButton();
        brnKonfiguracije = new javax.swing.JButton();
        btnKomponente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServisi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton3.setText("Klijenti");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kontrolna tabla");

        pnlServiser.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIme.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblIme.setText("Ime: ");

        lblPrezime.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblPrezime.setText("Prezime: ");

        lblKorisnickoIme.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblKorisnickoIme.setText("Korisnicko ime: ");

        btnKlijenti.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnKlijenti.setText("Pregled klijenata");
        btnKlijenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlijentiActionPerformed(evt);
            }
        });

        brnKonfiguracije.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        brnKonfiguracije.setText("Rad sa konfiguracijama");
        brnKonfiguracije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnKonfiguracijeActionPerformed(evt);
            }
        });

        btnKomponente.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnKomponente.setText("Dodavanje komponenti");
        btnKomponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKomponenteActionPerformed(evt);
            }
        });

        tblServisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Datum", "Opis", "Klijent"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblServisi);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Moji servisi");

        javax.swing.GroupLayout pnlServiserLayout = new javax.swing.GroupLayout(pnlServiser);
        pnlServiser.setLayout(pnlServiserLayout);
        pnlServiserLayout.setHorizontalGroup(
            pnlServiserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServiserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServiserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServiserLayout.createSequentialGroup()
                        .addGroup(pnlServiserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKorisnickoIme)
                            .addComponent(lblIme, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrezime, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlServiserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKomponente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKlijenti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(brnKonfiguracije, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlServiserLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlServiserLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlServiserLayout.setVerticalGroup(
            pnlServiserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServiserLayout.createSequentialGroup()
                .addGroup(pnlServiserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServiserLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblIme)
                        .addGap(28, 28, 28)
                        .addComponent(lblPrezime)
                        .addGap(22, 22, 22)
                        .addComponent(lblKorisnickoIme))
                    .addGroup(pnlServiserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnKlijenti)
                        .addGap(12, 12, 12)
                        .addComponent(btnKomponente)
                        .addGap(14, 14, 14)
                        .addComponent(brnKonfiguracije)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlServiser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnlServiser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlServiser.getAccessibleContext().setAccessibleName("Logovani Serviser");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKlijentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlijentiActionPerformed
            JFrame klijenti = new Klijenti();
            klijenti.setVisible(true);
    }//GEN-LAST:event_btnKlijentiActionPerformed

    private void btnKomponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKomponenteActionPerformed
        JFrame komponente = new Komponente();
        komponente.setVisible(true);
    }//GEN-LAST:event_btnKomponenteActionPerformed

    private void brnKonfiguracijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnKonfiguracijeActionPerformed
        JFrame konfiguracije = new KonfiguracijaPregled(this);
        konfiguracije.setVisible(true);
    }//GEN-LAST:event_brnKonfiguracijeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnKonfiguracije;
    private javax.swing.JButton btnKlijenti;
    private javax.swing.JButton btnKomponente;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblKorisnickoIme;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JPanel pnlServiser;
    private javax.swing.JTable tblServisi;
    // End of variables declaration//GEN-END:variables

    public void populate() {
        lblIme.setText("Ime: "+serviser.getServiserIme());
        lblPrezime.setText("Prezime: "+serviser.getServiserPrezime());
        lblKorisnickoIme.setText("Korisnicko ime: "+serviser.getKorisnickoIme());
        try {
            LinkedList<Servis> servisi = Controller.getInstance().getServices();
            LinkedList<Servis> servisiLogovanog = new LinkedList<>();
            for (Servis servis : servisi) {
                if (servis.getServiser().getServiserID()==Session.getInstance().getServiser().getServiserID()) {
                    servisiLogovanog.add(servis);
                }
            }
            TableModelServis tbs = new TableModelServis(servisiLogovanog);
            tblServisi.setModel(tbs);
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
