/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.clients;

import controller.Controller;
import domain.Klijent;
import form.configurations.KonfiguracijaUnos;
import java.awt.HeadlessException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Ivan
 */
public class KlijentiUnos extends javax.swing.JFrame {

    private Klijent klijent;
    private Klijenti parentKlijenti;
    private KonfiguracijaUnos parentKonfiguracija;

    /**
     * Creates new form KlijentiUnos
     */
    
    public KlijentiUnos() throws HeadlessException {
        initComponents();
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }

    public KlijentiUnos(Klijenti parent) {
        this.parentKlijenti = (Klijenti) parent;
        initComponents();
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }

    public KlijentiUnos(Klijenti parent, Klijent klijent) {
        this.parentKlijenti = (Klijenti) parent;
        initComponents();
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        txtIme.setText(klijent.getKlijentIme());
        txtPrezime.setText(klijent.getKlijentPrezime());
        txtBrTel.setText(klijent.getKlijentBrTel());

        this.klijent = klijent;
    }

        public KlijentiUnos(KonfiguracijaUnos parent) {
        this.parentKonfiguracija=(KonfiguracijaUnos) parent;
        initComponents();
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }

    public KlijentiUnos(KonfiguracijaUnos parent, Klijent klijent) {
        this.parentKonfiguracija=(KonfiguracijaUnos) parent;
        initComponents();
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        txtIme.setText(klijent.getKlijentIme());
        txtPrezime.setText(klijent.getKlijentPrezime());
        txtBrTel.setText(klijent.getKlijentBrTel());

        this.klijent = klijent;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBrTel = new javax.swing.JTextField();
        lblBrTel = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        lblPrezime = new javax.swing.JLabel();
        lblIme = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        lblPodaci = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBrTel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblBrTel.setText("Br. Tel:");

        lblPrezime.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblPrezime.setText("Prezime:");

        lblIme.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblIme.setText("Ime:");

        lblPodaci.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblPodaci.setText("Podaci o klijentu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(lblPodaci)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPrezime)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIme)
                        .addGap(18, 18, 18)
                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBrTel)
                        .addGap(18, 18, 18)
                        .addComponent(txtBrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPodaci)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIme)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrezime)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrTel)
                    .addComponent(txtBrTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnCancel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCancel.setText("Otkaži");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnSave.setText("Sačuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String brTel = txtBrTel.getText().trim();

        if (ime.isEmpty() && prezime.isEmpty() && brTel.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Popunite sva polja!", "Greska", JOptionPane.ERROR_MESSAGE);
        }

        Klijent klijentPop = getPopulatedClient();
        if (klijentPop != null) {

            try {
                if (this.klijent != null) {
                    klijent.setKlijentIme(ime);
                    klijent.setKlijentPrezime(prezime);
                    klijent.setKlijentBrTel(brTel);
                    Controller.getInstance().updateClient(klijent);
                    if (parentKlijenti==null) {
                        parentKonfiguracija.populateCmb();
                    }else parentKlijenti.populateCmb();
                    JOptionPane.showMessageDialog(this, "Klijent je uspešno izmenjen!", "Izmena klijenta", JOptionPane.INFORMATION_MESSAGE);

                    int result = JOptionPane.showConfirmDialog(this, "Napravite još izmena?", "Upit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (result == 0) {
                        txtIme.setText("");
                        txtPrezime.setText("");
                        txtBrTel.setText("");
                    }else 
                        dispose();
                } else {
                    Controller.getInstance().addClient(klijentPop);
                    if (parentKlijenti==null) {
                        parentKonfiguracija.populateCmb();
                    }else parentKlijenti.populateCmb();
                    JOptionPane.showMessageDialog(this, "Klijent je uspešno sačuvan!", "Dodavanje klijenta", JOptionPane.INFORMATION_MESSAGE);

                    int result = JOptionPane.showConfirmDialog(this, "Dodajte novog klijenta?", "Upit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (result == 0) {
                        txtIme.setText("");
                        txtPrezime.setText("");
                        txtBrTel.setText("");
                    }else 
                        dispose();
                }

            } catch (Exception ex) {
                Logger.getLogger(KlijentiUnos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentiUnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentiUnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentiUnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentiUnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentiUnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBrTel;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblPodaci;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JTextField txtBrTel;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private Klijent getPopulatedClient() {
        try {
            String ime = txtIme.getText().trim();
            String prezime = txtPrezime.getText().trim();
            String brTel = txtBrTel.getText().trim();

            if (ime.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Polje za ime ne sme biti prazno!", "Greska", JOptionPane.ERROR_MESSAGE);
                return null;
            }
            if (prezime.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Polje za prezime ne sme biti prazno!", "Greska", JOptionPane.ERROR_MESSAGE);
                return null;
            }
            if (brTel.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Polje za broj telefona ne sme biti prazno!", "Greska", JOptionPane.ERROR_MESSAGE);
                return null;
            }
            Klijent klijentPop = new Klijent(Controller.getInstance().getClientLastID(), ime, prezime, brTel, new LinkedList<>());
            return klijentPop;
        } catch (Exception ex) {
            Logger.getLogger(KlijentiUnos.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
}
